services:
#    config.example:
#        class: Kishron\ConfigBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    Conf:
        class: Kishron\ConfigBundle\Service\Conf
        arguments: ['@doctrine']
        
    app.twig_extension:
        class: Kishron\ConfigBundle\Twig\ConfigExtension
        public: false
        tags:
            - { name: twig.extension }
                       