<?php

namespace Kishron\ConfigBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfParameterRepository extends EntityRepository
{
}
