<?php

namespace Kishron\ConfigBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfCategoryRepository extends EntityRepository
{
}
